server:
  port: 0

spring:
  application:
    name: open-market-items
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  datasource:
    url: jdbc:postgresql://localhost:5433/open-market-items-db
    username: development
    password: development
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  flyway:
    schemas: public

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    hostname: localhost

java:
  io:
    tmpdir: ${TEMP_DIR_PATH}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  aws-secret-key: ${AWS_SECRET_KEY}