version: '3'

services:
  db-keycloak:
    container_name: "keycloak-db"
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      - open-market-network
  db-users-open-market:
    container_name: "open-market-users-db"
    image: 'bitnami/postgresql:16'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=open-market-users-db
    networks:
      - open-market-network
  db-items-open-market:
    container_name: "open-market-items-db"
    image: 'bitnami/postgresql:16'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=open-market-products-db
    networks:
      - open-market-network
  keycloak:
    container_name: "keycloak_open-market"
    image: "quay.io/keycloak/keycloak:22.0.0"
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    ports:
      - "8185:8080"
    volumes:
      - ./custom-user-storage-open-market/target:/opt/keycloak/providers
    depends_on: [ db-keycloak, db-users-open-market ]
    entrypoint: ["/opt/keycloak/bin/kc.sh", "--verbose", "start-dev"]
    networks:
      - open-market-network
  rabbitmq:
    container_name: "rabbitmq_open-market"
    image: 'rabbitmq:management'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - open-market-network

networks:
  open-market-network:
