spring:
  application:
    name: open-market-gateway
  cloud:
    gateway:
      routes:
        - id: users_route
          uri: lb://OPEN-MARKET-USERS
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}