spring:
  application:
    name: "open-market-discovery"

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF